---
title: "Anotación de Ensamblajes"
lang: es
date: today
execute: 
  eval: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
---

# Introducción
En esta práctica vamos a trabajar con los resultados de la anotación estructural realizada sobre el ensamblaje de la práctica anterior. Desafortunadamente, los ordenadores virtuales no están preparados para realizar la anotación. Pero a continuación se muestran las órdenes que en un terminal de Bash producirían los resultados. Voy a suponer que he estado trabajando como hasta ahora (desde PBioinformatica), a ver si puedo modificar las cosas correctamente.

# Datos
Las secuencias que vamos a anotar son el ensamblaje obtenido en la práctica anterior.

Las evidencias que usaremos para encontrar los genes són secuencias de proteínas que esperamos encontrar codificadas en los cóntigos. Normalmente usaríamos las proteínas conocidas de alguna especie próxima. Usaremos las 6023 proteínas que sabemos que codifica el cromosoma 4 de *Arabidopsis thaliana*. Las podéis descargar de Uniprot, y las meteremos en la carpeta data.

# Programas
Los programas que **NO** utilizaremos (porque no están instalados y son difíciles de instalar) son RepeatModeler (@Flynn2020), RepeatMasker, y GALBA (@Bruna2023). Cada uno de ellos, a su vez, utiliza otros.

## RepeatModeler
Utiliza como input sólo el ensamblaje, para identificar los elementos repetitivos que pueda haber. Genera, entre otras cosas, un archivo FASTA con las secuencias consenso de las familias de elementos transponibles identificadas. Este archivo FASTA se puede usar después para enmascarar el genoma.

## RepetaMasker
Su propósito es enmascarar del ensamblaje todas las instancias de elementos repetitivos que pueda identificar. Utiliza una librería de elementos repetitivos previamente conocidos. Existen bases de datos, como Dfam, que pueden usarse cuando queremos enmascarar el ensamblaje de un organismo parecido a aquellos de los que ya conocemos muchos elementos repetitivos. También podemos usar el archivo FASTA generado por RepeatModeler de novo.

## GALBA
Utiliza miniprot (@Li2023) para alinear las proteínas al ensamblaje i encontrar genes homólogos a los que las condifican. A partir de estos resultados, entrena a Augustus para definir mejor los bordes de los genes y posiblemente encontrar otros genes adicionales. No es el programa más preciso, pero es relativamente sencillo de usar.

# Resultados
## Modificación de los nombres de las proteínas
Al descargar las proteínas del cromosoma 4 de *A. thaliana*, el archivo FASTA contiene cabeceras demasiado extensas. Para facilitar el trabajo de GALBA vamos a modificar las cabeceras o nombres de las secuencias:

:::{.callout-note icon=false}
# Ejercicio 1
Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en un bloque de Bash de tu documento de Quarto de tal manera que el archivo de entrada esté en tu carpeta data y el de salida en la misma carpeta de trabajo de la práctica actual, y además, que sólo se ejecute si el archivo de salida proteinas.fasta no existe.

`awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}'`
:::

:::{.callout-note icon=false}
# Solución 1

```{bash}
cd "$(git rev-parse --show-toplevel)"

if [ ! -e ./results/21-04-2026/At4_corregido.fasta ]; then
zcat "./data/14-04-2026/At4.10.fa.gz" | awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' > "./results/21-04-2026/At4_corregido.fasta"
fi
```
:::

:::{.callout-warning icon=true}
Como estamos descomprimiendo primero, el archivo resultante está descomprimido y por tanto ocupa mucho (+200 Mb). Hay que ir con cuidado con estas cosas.
:::

## Análisis de los resultados de RepeatModeler
RepeatModeler fue ejecutado de la manera siguiente:

```{bash}
#| eval: false
# Paso previo para convertir el ensamblaje en una base de datos de BLAST:
BuildDatabase -name At4 ../2026-04-16/asm1/At4.fa

RepeatModeler -database At4 -threads 6 >& run.log
```

Puedes descargar y descomprimir los resultados de RepeatModeler desde el aula virtual a la carpeta de data (como si fueran resultados tuyos). Encontrarás la estructura de archivos siguiente:

```text
.
├── At4-families.fa               
├── At4-families.stk   
├── At4.nhr                     
├── At4.nin                           
├── At4.njs                           
├── At4.nnd                              
├── At4.nni               
├── At4.nog              
├── At4.nsq              
├── At4-rmod.log
├── At4.translation 
├── RM_358880.MonApr202033152026
│   ├── consensi.fa
│   ├── families.stk
│   ├── genome.2bit
│   ├── rmod.log
│   ├── round-1
│   ├── round-2
│   └── round-3
└── run.log

```



:::{.callout-note icon=false}
# Ejercicio 2

Explora los resultados de RepeatModeler y trata de contestar las preguntas siguientes.

1. ¿Cuántas familias de elementos transponibles se han encontrado?
2. ¿Cuánto duró la ejecución del programa?
3. ¿Cuál dirías que es el archivo de salida más importante?
:::

:::{.callout-note icon=false}
# Ejercicio 2
1. Para ver cuantas familias de elementos transponibles hemos encontrado, podemos hacer un conteo en At4-families.fa (el archivo fasta final):

```{bash}
cd "$(git rev-parse --show-toplevel)"

grep -c ">" ./data/21-04-2026/Modeler/At4-families.fa
```
y obtenemos que existen 24 familias diferentes. 

**¡ATENCIÓN!**: en `At4-rmod.log` aparecen también nombradas las familias en un cuadro de texto que dice algo como "Number of families returned by RECON = 1609"; pero esto no osn familias definitivas. Posteriormente, Modeler hace un filtrado y nos deja con las 24 familias que hemos obtenido.

2. Para saber cuanto duró la ejecución del programa, tenemos que entrar en alguno de los .log; ya sea `At4-rmod.log` o `rmod.log`; e ir abajo del todo, dónde nos aparece un texto que dice: "Program Time: 01:02:16 (hh:mm:ss) Elapsed Time". Por tanto, asumimos que el programa se ha estado ejecutando por algo más que 1h.

3. El archivo de salida más importante es `At4-families.fa`; puesto que es el archivo fasta con los resultados de nuestro análisis y que deberemos de usar para los procesados siguientes.
:::

## Suavizar la máscara
RepeatMasker fue ejecutado así (no en mi ordenador ni mi estructura):

```{bash}
#| eval: false
RepeatMasker -lib At4-families.fa -dir RM01 -gtf ../../data/At4.fa
```

Encontrarás la carpeta (comprimida) de resultados de RepeatMasker en el aula virtual. Descárgala y descomprimela en la carpeta data. La versión enmascarada tiene una máscara dura (RepeatMasker ha sustituído todos los elementos trasponibles y repeticiones por Ns), con lo que se ha perdido la información de la secuencia original en esas regiones. El programa GALBA recomienda partir de un ensamblaje con máscara suave, donde las regiones repetitivas están marcadas con letra minúscula. Para convertir la máscara dura en una máscara suave, utilizaremos bedtools:

:::{.callout-note icon=false}
# Ejercicio 3
1. Instala el programa bedtools siguiendo las instrucciones oportunas para tu sistema en la página oficial
2. Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo GFF que ha producido RepetaMasker como coordenadas de las regiones a enmascarar. Lee el manual de bedtools maskfasta en este enlace y genera el ensamblaje con máscara suave llamado At4.soft.fa.
:::

:::{.callout-note icon=false}
# Solución 3
1. Es muy fácil de instalar:

```{bash}
#| eval: false
sudo apt-get install bedtools
```

2. Es un poco complejo, pero lo intentamos:

```{bash}
cd "$(git rev-parse --show-toplevel)"

if [ ! -e ./data/14-04-2026/At4.10.fa ]; then
gunzip -c "./data/14-04-2026/At4.10.fa.gz" > "./data/14-04-2026/At4.10.fa"
fi

if [ ! -e ./results/21-04-2026/At4.soft.fa ]; then
bedtools maskfasta -fi "./data/14-04-2026/At4.10.fa" \
                   -bed "./data/21-04-2026/Masker/RM01/At4.fa.out.gff" \
                   -soft \
                   -fo "./results/21-04-2026/At4.soft.fa" 
fi

if [ -e ./data/14-04-2026/At4.10.fa ]; then
rm "./data/14-04-2026/At4.10.fa"
fi

```
:::

## GALBA
Para ejecutar GALBA ha sido necesario crear algunas variables de entorno que indican donde puede GALBA encontrar un par de ejecutables más. Para facilitar la reproducibilidad, este tipo de definiciones deben aparecer al principio del bloque, donde son más visibles, para que sean fácilmente modificadas cuando las órdenes vayan a ejecutarse en otro ordenador.

```{bash}
#| eval: false
export TSEBRA_PATH=/home/joiglu/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/home/joiglu/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```

:::{.callout-note icon=false}
# Ejercicio 4
Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción eval: false) como el anterior, donde los caminos TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta bin, aunque no los tengas instalados.
:::

:::{.callout-note icon=false}
# Solución 4
Como ya he mencionado en otros momentos, yo no tengo una carpeta bin propia en mi home, si no que uso otra diferente que se llama `/usr/local/bin`, que peretenece al propio PATH predeterminado de BASH. Por ello, mi código sería:

```{bash}
#| eval: false
export TSEBRA_PATH=/usr/local/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/usr/local/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```
:::





